version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: barber-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: barberapp
      POSTGRES_USER: barberuser
      POSTGRES_PASSWORD: barberpass123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - barber-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: barber-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@barber.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - barber-network

volumes:
  postgres_data:
    driver: local

networks:
  barber-network:
    driver: bridge
